// scripts/tempo-keygen.mjs
//
// UC8 · Task 1 — generate a FRESH, throwaway Tempo Testnet (Moderato) dev wallet.
//
// Writes TEMPO_DEV_PRIVATE_KEY / TEMPO_DEV_ADDRESS / TEMPO_RPC_URL into .env.local,
// which is gitignored (the repo's `.env*` rule) and is where every other secret in
// this repo lives (UC5_BOT_SIGNER_PRIVATE_KEY, UC6_PRIVATE_KEY, ...).
//
// SECURITY:
//   - The private key is crypto-random and has never held real funds. Throwaway only.
//   - The key is written ONLY to the gitignored env file and is NEVER printed.
//   - Idempotent: it refuses to overwrite an existing key.
//
// Run once from the repo root:  node scripts/tempo-keygen.mjs
import { readFileSync, appendFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const ENV_PATH = resolve(process.cwd(), ".env.local");
const existing = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf8") : "";

// Idempotent guard — never clobber a key that already exists.
if (/^TEMPO_DEV_PRIVATE_KEY=0x[0-9a-fA-F]{64}\s*$/m.test(existing)) {
  const addr = existing.match(/^TEMPO_DEV_ADDRESS=(0x[0-9a-fA-F]{40})\s*$/m);
  console.log("TEMPO_DEV_PRIVATE_KEY already present in .env.local — not regenerating.");
  if (addr) console.log("Existing TEMPO_DEV_ADDRESS:", addr[1]);
  process.exit(0);
}

const pk = generatePrivateKey(); // 32-byte crypto-random — fresh & throwaway
const account = privateKeyToAccount(pk); // derive the address

const block =
  "\n# ── UC8 · Tempo Testnet (Moderato) throwaway dev wallet ──\n" +
  "# Generated by scripts/tempo-keygen.mjs. Gitignored via the .env* rule. Never held real funds.\n" +
  `TEMPO_DEV_PRIVATE_KEY=${pk}\n` +
  `TEMPO_DEV_ADDRESS=${account.address}\n` +
  "TEMPO_RPC_URL=https://rpc.moderato.tempo.xyz\n";

appendFileSync(ENV_PATH, block, "utf8");

// Print ONLY the address — never the key.
console.log("Generated a fresh, throwaway Tempo dev wallet.");
console.log("TEMPO_DEV_ADDRESS:", account.address);
console.log("Private key written to .env.local (gitignored) — not shown.");
